language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

cache:
  directories:
    - vendor

before_script:
  - composer install --no-interaction

script:
  - composer run test

sudo: false